# this is the application for bitnami's helm chart (pull remotely) for redis version 16.12.1

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: redis
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.12.1
    helm:
      releaseName: redis
  destination:
    server: "in-cluster"
    namespace: redis
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true