apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '16.12.1'
    chart: redis
    helm:
      valueFiles:
      - values.yaml
  destination:
    name: in-cluster
    namespace: redis